name : CD Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
    TF_VAR_environment : "dev"
    TF_VAR_location : "uksouth"
    ACR_LOGIN_SERVER: ${{ secrets.ACR_NAME }}.azurecr.io
    TF_VAR_acr_id : ${{ secrets.ACR_ID }}

jobs:
    build:
        name: Build & Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Login to ACR
              uses: azure/docker-login@v1
              with:
                login-server: ${{ env.ACR_LOGIN_SERVER }}
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}

            - name: Pull Frontend Image
              run: |
                docker pull ${{ env.ACR_LOGIN_SERVER }}/team3-front-app:latest || true
        
            - name: Pull Backend Image
              run: |
                docker pull ${{ env.ACR_LOGIN_SERVER }}/team3-back-app:latest || true

            - name: Push Frontend Image to ACR
              run: docker push ${{ env.ACR_LOGIN_SERVER }}/team3-front-app:latest

            - name: Push Backend Image to ACR
              run: docker push ${{ env.ACR_LOGIN_SERVER }}/team3-back-app:latest
            
    terraform-plan:
        name: Terraform Plan
        runs-on: ubuntu-latest
        needs: build
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
        steps:
            - uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.5.0

            - name: Terraform Init
              working-directory: ./my-infrastructure
              run: terraform init

            - name: Terraform Plan
              working-directory: ./my-infrastructure
              run: terraform plan
              
    terraform-apply:
        name: Terraform Apply
        runs-on: ubuntu-latest
        needs: terraform-plan
        env:
            ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        steps:
            - uses: actions/checkout@v2

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.5.0

            - name: Terraform Init
              working-directory: ./my-infrastructure
              run: terraform init

            - name: Terraform Apply
              working-directory: ./my-infrastructure
              run: terraform apply -auto-approve